/* (Beta) Export of data model RainFallRadarObserved of the subject dataModel.Environment for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE RainFallRadarObserved_type AS ENUM ('RainFallRadarObserved');
CREATE TABLE RainFallRadarObserved (
  "address" JSON,
  "alternateName" TEXT,
  "areaServed" TEXT,
  "atmosphericPressure" NUMERIC,
  "cellsSize" NUMERIC,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "dateObserved" TIMESTAMP,
  "dateObservedFrom" TIMESTAMP,
  "dateObservedTo" TIMESTAMP,
  "description" TEXT,
  "feelsLikeTemperature" NUMERIC,
  "gustSpeed" NUMERIC,
  "id" TEXT PRIMARY KEY,
  "illuminance" NUMERIC,
  "location" JSON,
  "mapScale" TEXT,
  "measuredArea" NUMERIC,
  "name" TEXT,
  "numberOfCol" NUMERIC,
  "numberOfRow" NUMERIC,
  "owner" JSON,
  "rainFallRadarContent" TEXT,
  "refDevice" JSON,
  "refPointOfInterest" JSON,
  "relativeHumidity" NUMERIC,
  "seeAlso" JSON,
  "source" TEXT,
  "temperature" NUMERIC,
  "type" RainFallRadarObserved_type,
  "visibility" JSON,
  "weatherType" TEXT,
  "windDirection" NUMERIC,
  "windSpeed" NUMERIC
);